CREATE TABLE IF NOT EXISTS user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  account_id VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) UNIQUE NOT NULL,
  hashed_passwd VARCHAR(255) NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
