version: "3"
services: 
  fe:
    image: $DOCKER_IMAGE_FE:$FE_TAG
    restart: always
    ports:
      - $FE_HOST_PORT:80
    environment:
      TZ: Asia/Shanghai
      FLASK_ENV: production
    volumes: 
      - $CM_DIR/fe:/etc/nginx/conf.d/





